name: Jarvis Yang 's  Blog
description: Work & Code & Life & Other ...
# meta_description: "meta life bloging"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://yangyueyang.com'
# google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'www.yangyueyang.com'
author:         'Jarvis Yang'

parse_block_html: true