name: Jarvis Yang 's  Blog
description: Technology & Coding & LifeLog ...

markdown: kramdown
#highlighter: pygments
highlighter: rouge
logo: false
domain_name: 'http://jarvisyang.com'
# google_analytics: 'UA-XXXXXXXX-X'

plugins: [jekyll-paginate]
paginate: 6
# Details for the RSS feed generator
url:            'www.jarvisyang.com'
author:         'Jarvis Yang'

parse_block_html: true
