name: Jarvis Yang 's  Blog
description: Work & Code & Life & Other ...

markdown: kramdown
#highlighter: pygments
highlighter: rouge
logo: false
domain_name: 'http://yangyueyang.com'
# google_analytics: 'UA-XXXXXXXX-X'
#gems: [jekyll-paginate]
plugins: [jekyll-paginate]
paginate: 5
# Details for the RSS feed generator
url:            'www.yangyueyang.com'
author:         'Jarvis Yang'

parse_block_html: true